In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import bootstrapped.bootstrap as bs
import bootstrapped.stats_functions as bs_stats
from scipy.stats import bootstrap

(b)

In [3]:
#find all folder's paths
path_list = []
bending_path = []
for root, dirs, files in os.walk(os.getcwd()):
    for f in files:
        fullpath = os.path.join(root,f)
        if f.find("dataset1.csv")>=0:
            path_list.append(root)
        if "dataset1.csv" in fullpath and 'bending' in fullpath :
            bending_path.append(fullpath)
        
#concat all training set
training = pd.DataFrame()
counter = 0
for path in path_list: #len = 7
    if path != bending_path[0][:-len('dataset1.csv')-1] and path != bending_path[1][:-len('dataset1.csv')-1]:
        for i in range(4,16):
            csv_name = '/dataset'+str(i)+'.csv'
            df_skip = pd.read_csv(path + csv_name,skiprows = 5, header = None,names=['time','avg_rss12','var_rss12','avg_rss13','var_rss13','avg_rss23','var_rss23'])
            index = path.find('AReM')
            df_skip['label'] = path[index+5:]
            training = pd.concat([training, df_skip], ignore_index=True)
            
    elif path == bending_path[0][:-len('dataset1.csv')-1]:
        for i in range(3, 8):
            csv_name = '/dataset'+str(i)+'.csv'
            df_skip = pd.read_csv(path + csv_name,skiprows = 5, header = None,names=['time','avg_rss12','var_rss12','avg_rss13','var_rss13','avg_rss23','var_rss23'])
            index = path.find('AReM')
            df_skip['label'] = path[index+5:]
            training = pd.concat([training, df_skip], ignore_index=True)
            counter +=1
    elif path == bending_path[1][:-len('dataset1.csv')-1]:
        for i in range(3, 7):
            csv_name = '/dataset'+str(i)+'.csv'
            df_skip = pd.read_csv(path + csv_name,skiprows = 5, header = None,names=['time','avg_rss12','var_rss12','avg_rss13','var_rss13','avg_rss23','var_rss23'])
            df_skip['label'] = path[index+5:]
            training = pd.concat([training, df_skip], ignore_index=True)
            counter +=1
print(training)

         time  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0           0      41.50       0.50      20.67       0.47      14.33
1         250      41.50       0.50      20.00       0.00      15.25
2         500      41.50       0.50      20.25       0.43      15.75
3         750      41.67       0.47      20.75       0.43      17.50
4        1000      41.50       0.50      21.00       0.00      16.50
...       ...        ...        ...        ...        ...        ...
33114  118750      38.00       2.55      18.25       2.17      20.00
33115  119000      36.00       0.00      19.00       1.41      13.67
33116  119250      37.00       1.73      17.75       0.43      22.50
33117  119500      37.00       3.74      19.00       4.18      22.00
33118  119750      38.75       1.92      16.75       3.49      21.00

       var_rss23     label
0           0.47  standing
1           0.43  standing
2           0.43  standing
3           0.50  standing
4           1.12  standing
...          ...       ...
33114       4.74   cycling
33115       1.25   cycling
33116       0.87   cycling
33117       1.41   cycling
33118       3.67   cycling

[33119 rows x 8 columns]

In [4]:
#concat all testing set
testing = pd.DataFrame()
for path in path_list: 
    for i in range(1,3):
        csv_name = '/dataset'+str(i)+'.csv'
        df_skip = pd.read_csv(path + csv_name,skiprows = 5, header = None, names=['time','avg_rss12','var_rss12','avg_rss13','var_rss13','avg_rss23','var_rss23'])
        index = path.find('AReM')
        df_skip['label'] = path[index+5:]
        testing = pd.concat([testing, df_skip], ignore_index=True)

for path in path_list: 
    if path != bending_path[0][:-len('dataset1.csv')-1] and path != bending_path[1][:-len('dataset1.csv')-1]:
        csv_name = '/dataset3.csv'
        df_skip = pd.read_csv(path + csv_name,skiprows = 5, header = None, names=['time','avg_rss12','var_rss12','avg_rss13','var_rss13','avg_rss23','var_rss23'])
        df_skip['label'] = path[index+5:]
        testing = pd.concat([testing, df_skip], ignore_index=True)

print(testing)

        time  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0          0      46.50       0.50      11.50       0.50      20.33
1        250      46.50       0.50      12.00       0.00      20.25
2        500      46.50       0.50      12.00       0.00      20.50
3        750      46.50       0.50      12.75       0.43      19.50
4       1000      46.50       0.50      13.25       0.43      18.75
...      ...        ...        ...        ...        ...        ...
9115  118750      36.50       1.50      15.67       9.74      20.50
9116  119000      36.00       0.00      23.25       1.30      17.00
9117  119250      32.33       5.56      15.33       3.77      14.50
9118  119500      32.00       5.87      12.25       2.17      14.50
9119  119750      38.00       2.12      16.50       3.20      11.25

      var_rss23     label
0          0.94  standing
1          0.43  standing
2          0.50  standing
3          0.50  standing
4          0.43  standing
...         ...       ...
9115       2.87   cycling
9116       1.63   cycling
9117       4.82   cycling
9118       2.87   cycling
9119       5.80   cycling

[9120 rows x 8 columns]

(c) i. mean, median, minimum, maximum, standard deviation, first quartile, and third quartile

(c) ii
Extract the time-domain features minimum, maximum, mean, median, standard deviation, first quartile, and third quartile for all of the 6 time series in each instance. You are free to normalize/standardize features or use them
directly.

Empty DataFrame
Columns: [min1, max1, mean1, med1, std1, q11, q31, label1, min2, max2, mean2, med2, std2, q12, q32, label2, min3, max3, mean3, med3, std3, q13, q33, label3, min4, max4, mean4, med4, std4, q14, q34, label4, min5, max5, mean5, med5, std5, q15, q35, label5, min6, max6, mean6, med6, std6, q16, q36, label6]
Index: []

[0 rows x 48 columns]

In [160]:
temp_nested_list = []
paths_csv = []
for root,  dirs, files in os.walk(os.getcwd()):
    for f in files:
        fullpath = os.path.join(root,f)
        if not f.startswith('.') and f.endswith('.csv'):
            end = fullpath.find('dataset')          
            start = fullpath.find('AReM/')
            label = fullpath[start+5: end-1]
            paths_csv.append([fullpath,label])
            #path will be paths_csv[i][0], label will be paths_csv[i][1]
            
feature_cols = ['avg_rss12','var_rss12','avg_rss13','var_rss13','avg_rss23','var_rss23']
for i in feature_cols:
    min_n = dict()
    max_n = dict()
    mean_n = dict()
    med_n = dict()
    std_n = dict()
    q1_n = dict()
    q3_n = dict()
    label_n = dict()

for col in feature_cols:
    min_n [col] = list()
    max_n [col]= list()
    mean_n[col] = list()
    med_n[col] = list()
    std_n[col] = list()
    q1_n[col]= list()
    q3_n[col] = list()
    label_n[col] = list()

for index in range(0,len(paths_csv)):
    df = pd.read_csv(paths_csv[index][0],skiprows = 5, header = None, names= ['time','avg_rss12','var_rss12','avg_rss13','var_rss13','avg_rss23','var_rss23'])
    df['label'] = paths_csv[index][1]
    #print(df)
    #df = df_tem.iloc[: , 1:]
    
    
    for i in feature_cols:
        #if i==feature_cols[3] and index==57: 
        #print('Hello', index, paths_csv[index], '\n')
        min_n[i].append(np.nanmin(df[i]))
        max_n[i].append(np.nanmax(df[i]))
        mean_n[i].append(np.nanmean(df[i]))
        med_n[i].append(np.nanmedian(df[i]))
        std_n[i].append(np.nanstd(df[i]))
        q1_n[i].append(np.nanquantile(df[i],0.25))
        q3_n[i].append(np.nanquantile(df[i],0.75))
        label_n[i].append(df['label'][0])
#print(len(label_n['avg_rss12']))

In [254]:
list_dict = [min_n, max_n, mean_n, med_n, std_n, q1_n, q3_n,label_n]
time_domain_name = ['min','max','mean','med','std','q1','q3','label']
#list_dict[0]['avg_rss12']
#list_dict[0].keys()


schema = []
num_records = len (min_n[feature_cols[0]])
list_2d_temp = list () 
for record_index in range (0, num_records):
    record = list () 
    for col_index in range (1, len (feature_cols) + 1):
        col = feature_cols [col_index-1]
        for metric_index in range (0, len (time_domain_name)):
            metric_name = time_domain_name [metric_index] + str (col_index)
            cell = list_dict [metric_index][col][record_index]
            record.append (cell)
            if metric_name not in schema: schema.append (metric_name)
    list_2d_temp.append (record)

#print (schema)
#print(list_2d_temp[0])


feature_desc = pd.DataFrame(list_2d_temp, columns = schema)
feature_desc

,min1,max1,mean1,med1,std1,q11,q31,label1,min2,max2,...,q35,label5,min6,max6,mean6,med6,std6,q16,q36,label6
0,33.33,48.00,44.334729,45.00,2.474358,42.2500,46.50,standing,0.0,3.90,...,17.7500,standing,0.0,5.02,0.933000,0.830,0.672907,0.4700,1.2500,standing
1,35.50,48.00,46.224938,46.00,1.746493,45.2500,48.00,standing,0.0,4.50,...,15.2500,standing,0.0,6.00,0.882583,0.830,0.667727,0.4700,1.1200,standing
2,36.00,47.33,44.441187,45.00,2.415277,44.6275,45.75,standing,0.0,4.50,...,14.6700,standing,0.0,5.91,1.155083,0.940,0.841210,0.5000,1.5000,standing
3,35.50,46.25,43.174938,43.67,1.986979,42.5000,44.50,standing,0.0,2.12,...,16.5000,standing,0.0,5.72,0.911979,0.830,0.665467,0.4700,1.2200,standing
4,29.75,48.00,46.932208,47.50,1.830755,47.2375,47.75,standing,0.0,4.60,...,15.5000,standing,0.0,6.58,0.991125,0.830,0.854438,0.4700,1.2200,standing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,19.00,43.75,35.879875,36.00,4.610068,33.0000,39.50,cycling,0.0,11.20,...,19.6900,cycling,0.0,8.50,3.093021,2.930,1.624339,1.8900,4.0600,cycling
84,25.33,45.00,37.114313,36.25,3.706518,34.5000,40.25,cycling,0.0,10.84,...,18.5000,cycling,0.0,9.50,3.076354,2.770,1.822633,1.7000,4.0375,cycling
85,27.00,45.00,36.819521,36.00,3.896394,33.7500,40.25,cycling,0.0,10.47,...,19.2700,cycling,0.0,8.99,2.887563,2.525,1.721298,1.5600,3.7700,cycling
86,27.75,44.67,37.144833,36.33,3.754986,34.0000,40.50,cycling,0.0,10.76,...,18.7500,cycling,0.0,8.75,2.822437,2.590,1.635476,1.5800,3.7400,cycling
87,19.00,44.00,36.228396,36.00,3.524939,34.0000,39.00,cycling,0.0,12.28,...,18.0625,cycling,0.0,9.98,3.480688,3.340,1.825864,2.1025,4.5500,cycling

c. iii) est. std of each of the time-domain features. then build 90% bootsrap confidene interval;

In [256]:
feature_desc = feature_desc.drop(columns=['label1','label2','label3','label4','label5'])
feature_desc

,min1,max1,mean1,med1,std1,q11,q31,min2,max2,mean2,...,q15,q35,min6,max6,mean6,med6,std6,q16,q36,label6
0,33.33,48.00,44.334729,45.00,2.474358,42.2500,46.50,0.0,3.90,0.432958,...,9.33,17.7500,0.0,5.02,0.933000,0.830,0.672907,0.4700,1.2500,standing
1,35.50,48.00,46.224938,46.00,1.746493,45.2500,48.00,0.0,4.50,0.312354,...,12.00,15.2500,0.0,6.00,0.882583,0.830,0.667727,0.4700,1.1200,standing
2,36.00,47.33,44.441187,45.00,2.415277,44.6275,45.75,0.0,4.50,0.346604,...,11.00,14.6700,0.0,5.91,1.155083,0.940,0.841210,0.5000,1.5000,standing
3,35.50,46.25,43.174938,43.67,1.986979,42.5000,44.50,0.0,2.12,0.506583,...,12.75,16.5000,0.0,5.72,0.911979,0.830,0.665467,0.4700,1.2200,standing
4,29.75,48.00,46.932208,47.50,1.830755,47.2375,47.75,0.0,4.60,0.429667,...,11.67,15.5000,0.0,6.58,0.991125,0.830,0.854438,0.4700,1.2200,standing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,19.00,43.75,35.879875,36.00,4.610068,33.0000,39.50,0.0,11.20,3.414312,...,14.75,19.6900,0.0,8.50,3.093021,2.930,1.624339,1.8900,4.0600,cycling
84,25.33,45.00,37.114313,36.25,3.706518,34.5000,40.25,0.0,10.84,2.730000,...,14.75,18.5000,0.0,9.50,3.076354,2.770,1.822633,1.7000,4.0375,cycling
85,27.00,45.00,36.819521,36.00,3.896394,33.7500,40.25,0.0,10.47,2.600146,...,15.50,19.2700,0.0,8.99,2.887563,2.525,1.721298,1.5600,3.7700,cycling
86,27.75,44.67,37.144833,36.33,3.754986,34.0000,40.50,0.0,10.76,2.419062,...,15.00,18.7500,0.0,8.75,2.822437,2.590,1.635476,1.5800,3.7400,cycling
87,19.00,44.00,36.228396,36.00,3.524939,34.0000,39.00,0.0,12.28,2.831687,...,14.00,18.0625,0.0,9.98,3.480688,3.340,1.825864,2.1025,4.5500,cycling

In [259]:
# est. std of each of the time-domain features.
std_features = []
for name in feature_desc.columns:
    std_features.append(feature_desc[name].values)
    
std_list = []
for index in range(0,len(std_features)-1):    
    tem = np.std(std_features[index])
    std_list.append(tem)
print(std_list)
print(len(std_list))

[9.515445066931843, 4.36932238296287, 5.305314461239687, 5.409056425357996, 1.7602191698745813, 6.118526249454473, 5.109642753365408, 0.0, 5.033881679163114, 1.5651942520745679, 1.4041971241720508, 0.8781516314077898, 0.9409936333203217, 2.1131565277371136, 2.9396159844182215, 4.8473579111726695, 3.9855401730280384, 4.013396722341803, 0.9403347763270604, 4.196608356067418, 4.1478580691355535, 0.0, 2.171183073234498, 1.159469512097659, 1.139058054228987, 0.4551557623199605, 0.8388126951078968, 1.543657928587387, 6.089106551460676, 5.7085244261061385, 5.643253378646845, 5.780655201421558, 1.0179958541711265, 6.061727225339022, 5.500200189394758, 0.045576965827593074, 2.50456803477282, 1.1482317454684954, 1.080283538057551, 0.5141316816102194, 0.754261365241397, 1.514917579004774]
42

In [258]:
#bootstrap 

cols_name = feature_desc.columns[:-1]

for col in cols_name: 
    data = (feature_desc[col].tolist(),)
    bt [col] = bootstrap (data, np.std, confidence_level=0.9).confidence_interval

for col in cols_name:
    print (col, bt[col])

/home/cheng/.local/lib/python3.10/site-packages/scipy/stats/_resampling.py:118: RuntimeWarning: invalid value encountered in double_scalars
  a_hat = num / den
/home/cheng/.local/lib/python3.10/site-packages/scipy/stats/_resampling.py:92: DegenerateDataWarning: The bootstrap distribution is degenerate; the confidence interval is not defined.
  warnings.warn(DegenerateDataWarning(msg))

min1 ConfidenceInterval(low=8.52630283504159, high=11.166846288038796)
max1 ConfidenceInterval(low=3.511181614954591, high=5.506577862896644)
mean1 ConfidenceInterval(low=4.781672230338426, high=5.968138974093533)
med1 ConfidenceInterval(low=4.89389989863533, high=6.135049361816101)
std1 ConfidenceInterval(low=1.598977564031534, high=1.988580431590388)
q11 ConfidenceInterval(low=5.643169299150053, high=6.717221705455872)
q31 ConfidenceInterval(low=4.458636165958164, high=5.961589270634911)
min2 ConfidenceInterval(low=nan, high=nan)
max2 ConfidenceInterval(low=4.672626127885434, high=5.445537071354766)
mean2 ConfidenceInterval(low=1.4102350143233773, high=1.7123499013684984)
med2 ConfidenceInterval(low=1.248388239105794, high=1.5513743185614046)
std2 ConfidenceInterval(low=0.806061491487283, high=0.9424316962690065)
q12 ConfidenceInterval(low=0.8394995973761402, high=1.036847644101877)
q32 ConfidenceInterval(low=1.914108058940792, high=2.303930214694724)
min3 ConfidenceInterval(low=2.7805692376491393, high=3.126922388384112)
max3 ConfidenceInterval(low=4.268618722538509, high=5.528484326587789)
mean3 ConfidenceInterval(low=3.489609320546318, high=4.554459346757816)
med3 ConfidenceInterval(low=3.504622708908938, high=4.597429487313632)
std3 ConfidenceInterval(low=0.804739324897035, high=1.1993475434603331)
q13 ConfidenceInterval(low=3.7013325824092256, high=4.776299001426379)
q33 ConfidenceInterval(low=3.6080631276142596, high=4.764357877731777)
min4 ConfidenceInterval(low=nan, high=nan)
max4 ConfidenceInterval(low=2.0046479713174494, high=2.3936930619148264)
mean4 ConfidenceInterval(low=1.0762249828706114, high=1.217683172734212)
med4 ConfidenceInterval(low=1.056233941211488, high=1.1976076508743807)
std4 ConfidenceInterval(low=0.4234251920157087, high=0.48801101341676933)
q14 ConfidenceInterval(low=0.7766147326081713, high=0.89070529768833)
q34 ConfidenceInterval(low=1.4346029847625, high=1.6227101457971576)
min5 ConfidenceInterval(low=4.757092557925232, high=7.880882987253714)
max5 ConfidenceInterval(low=4.8892589158942465, high=6.673201499889502)
mean5 ConfidenceInterval(low=4.61322266953801, high=6.914183919405128)
med5 ConfidenceInterval(low=4.7327849302221, high=7.113362149871375)
std5 ConfidenceInterval(low=0.8600244977269328, high=1.2914909134129462)
q15 ConfidenceInterval(low=5.020697790552345, high=7.426656458794708)
q35 ConfidenceInterval(low=4.545023196438829, high=6.748841784864109)
min6 ConfidenceInterval(low=0.0, high=0.07802896990623483)
max6 ConfidenceInterval(low=2.2925287095241855, high=2.827908337153203)
mean6 ConfidenceInterval(low=1.0652111661446215, high=1.212829033998005)
med6 ConfidenceInterval(low=0.9968970285982177, high=1.1464142067568677)
std6 ConfidenceInterval(low=0.48192814432884423, high=0.5459591860623579)
q16 ConfidenceInterval(low=0.6967800176399328, high=0.8100981879247773)
q36 ConfidenceInterval(low=1.4021368645578653, high=1.5954452045150946)